name: Release Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    uses: ./.github/workflows/build-and-release.yml
    with:
      tag: ${{ github.ref_name }}
    permissions:
      contents: write
